### ISSUE TITLE
Different stucture in Defs schema files

### ISSUE THREAD

**Issue by jetgeo** [OvertureMaps/schema#170]
Two of the defs.yaml files have a different structure than the others. Is this by intention? It is kind of confusing and makes traversing more complicated.
- https://github.com/OvertureMaps/schema/blob/main/schema/divisions/defs.yaml has "typeDefinitions" where other files have "propertyDefinitions". The content seems to describe properties like any other file.
- https://github.com/OvertureMaps/schema/blob/main/schema/buildings/defs.yaml does not have the levels "$defs" and "propertyContainers" but goes directly to the container "shapeContainer"

(I am not sure whether to write this as an issue or a discussion topic, but it seems like an issue to me)

**Comment by jenningsanderson** [comment]
Fixed for July release
