### ISSUE TITLE
Typo on Schema Docs

### ISSUE THREAD

**Issue by katrinayfmei** [OvertureMaps/schema#232]
On the website, there is a typo for the schema docs. On the page linked above for the Empire State Building example there are typos at:

https://docs.overturemaps.org/schema/

Buiding -> Building
` "primary": "Empire State Buiding"`

**Comment by jenningsanderson** [comment]
https://github.com/OvertureMaps/schema/pull/222

**Comment by danabauer** [comment]
Thanks for letting us know. This will be fixed in the next release.
