### ISSUE TITLE
404 error on https://schema.overturemaps.org/

### ISSUE THREAD

**Issue by wipfli** [OvertureMaps/schema#242]
The link https://schema.overturemaps.org/ results in a 404 page not found error. Is this still the correct link?

![image](https://github.com/user-attachments/assets/df8e0e18-245e-41cb-8f93-5eb1c3e72909)

**Comment by jenningsanderson** [comment]
Whoops! Nope, it's here: https://docs.overturemaps.org/schema/ — I just updated it, thanks!
