### ISSUE TITLE
Two dead/wrong links for the places catogories csv file

### ISSUE THREAD

**Issue by jconterra** [OvertureMaps/schema#281]
On https://docs.overturemaps.org/guides/places/ there are two dead/wrong links 
![image](https://github.com/user-attachments/assets/33ad1990-c0ee-48c2-8acc-8b92f3ba82ef) and 
![image](https://github.com/user-attachments/assets/56cc45d5-1bd0-48cb-a79f-1d3c636a7716).

**Comment by jenningsanderson** [comment]
Fixed in https://github.com/OvertureMaps/docs/pull/112
