### ISSUE TITLE
Broken category

### ISSUE THREAD

**Issue by Cj-Malone** [OvertureMaps/schema#40]
`charity_organization` references `community_organization`, but it doesn't exist.

```
charity_organization;[charity_organization,community_organization]
```
https://github.com/OvertureMaps/schema/blob/main/task-force-docs/places/overture_categories.csv#L1536C44-L1536C66

It should probably be:
```patch
-charity_organization;[charity_organization,community_organization]
+charity_organization;[public_service_and_government,organization,social_service_organizations,charity_organization]
```

**Comment by BramVanmeirhaeghe-TomTom** [comment]
@Cj-Malone What does "it doesn't exist" mean? It's nowhere to be found in the data? 
And do we have unmapped public_service_and_government,organization,social_service_organizations,charity_organization then? 

I think it's fine the make the update. Could you initiate a PR? 
cc @JanCallewaert-TomTom

**Comment by Cj-Malone** [comment]
I don't have numbers on what categories exist in the data, I can get you that next week. I mean the Overture categories look an awful lot like a tree, with 22 top categories.

```
eat_and_drink
accommodation
automotive
arts_and_entertainment
attractions_and_activities
active_life
beauty_and_spa
education
financial_service
private_establishments_and_corporates
retail
health_and_medical
pets
business_to_business
public_service_and_government
religious_organization
real_estate
travel
mass_media
home_service
professional_services
structure_and_geography
```

Every other category can be traced up to them, eg `afghan_restaurant` -> `restaurant` -> `eat_and_drink`.

However `charity_organization` only references `community_organization`, which doesn't exist in the tree. I believe it should be `charity_organization` -> `social_service_organizations` -> `organization` -> `public_service_and_government`.

**Comment by Cj-Malone** [comment]
Categories from the 2023-10-19 data: https://gist.github.com/Cj-Malone/ddf2200654fd0ad7219d3917f829caee

**Comment by jwass** [comment]
You can grab the distinct set of categories and counts with an athena query like this (I assume it'll work on duckdb also)
```
select t.category,
	count(1)
from overture_2023_10_19_alpha_0
	cross join unnest(categories.main || categories.alternate) as t(category)
where theme = 'places'
	and type = 'place'
group by t.category
order by 2 desc
```
Here's the result - it takes 3.5 seconds in Athena.
[adbfa6fd-a0ae-4cc8-87b8-616986c04ea0.csv](https://github.com/OvertureMaps/schema/files/13069411/adbfa6fd-a0ae-
4cc8-87b8-616986c04ea0.csv)
