### ISSUE TITLE
Schema for bbox

### ISSUE THREAD

**Issue by tschaub** [OvertureMaps/schema#74]
I don't see `bbox` referenced in the schema files, but I do see `bbox` columns in the 2023-10-19-alpha.0 released Parquet files (e.g. `s3://overturemaps-us-west-2/release/2023-10-19-alpha.0/theme=buildings/type=building/part-00765-87dd7d19-acc8-4d4f-a5ba-20b407a79638.c000.zstd.parquet`).

In Parquet, the `bbox` looks like this:
```
{
   ... other fields
  required group bbox {
    optional double minx;
    optional double maxx;
    optional double miny;
    optional double maxy;
  }
}
```

So the `bbox` is required, but the nested `minx`, `maxx`, `miny`, and `maxy` fields are optional (or nullable).  I was curious if this was leveraged anywhere in the data (should clients be prepared to handle null `minx` etc?) or if it should be changed in the schema to make those fields required.

Let me know if this is a better issue for the [data repo](https://github.com/OvertureMaps/data) or for a discussion instead.

**Comment by jwass** [comment]
Thanks, @tschaub. The fields `minx, maxx` etc. should indeed be required in the output Parquet schema. We'll look to get it fixed asap.

**Comment by jwass** [comment]
I figured I'd double-checked too that the individual bbox member fields are never null. Using Athena and defining a table `overture_2023_10_19_alpha_0` pointed to the `s3://overturemaps-us-west-2/release/2023-10-19-alpha.0` parquet files. 

```
select *
from overture_2023_10_19_alpha_0
where bbox.minx IS NULL
	OR bbox.maxx IS NULL
	OR bbox.miny IS NULL
	OR bbox.maxy IS NULL
```
returns no rows.

**Comment by jenningsanderson** [comment]
I will add here that `bbox` is only part of the data distribution (parquet files), not (officially) part of the _data schema_. Though, we should make this more explicit, perhaps we can expand on https://docs.overturemaps.org/#key-specifications point 2 to say something like the following: 

While Overture data is distributed in a cloud-native format, we use GeoJSON as a _mental model_ for individual features. Therefore, all features present in an Overture data release can be represented as GeoJSON. When representing an Overture feature as GeoJSON, the following rules are observed regarding the construction of the root-level GeoJSON properties: 

|GeoJSON Property| Presence  | Overture Dataset Property/Column|
|----------------|-----------|---------------------------------|
| `id`           | Required  | `id` |
| `geometry`     | Required  | GeoJSON representation of the WKB in `geometry`
| `properties`   | Required  | JSON representation of all columns relevant to the feature's theme + type. |
| `bbox` | Optional | Can be reconstructed from the `bbox` struct present in the Overture data release. |

**Comment by jenningsanderson** [comment]
Closing this issue as resolved; the bbox column in the beta release is in the form of `xmin, xmax`, etc. Please re-open if necessary
